### ISSUE TITLE
m3u Group Issues

### ISSUE THREAD

**Issue by SimoneGold** [jjssoftware/m3u-epg-editor#11] opened 2018-06-12 23:42 UTC
Hello,

I am getting this with my m3u:

**
2018-06-12T19:06:19.990000 performing HTTP GET request to file:///C:\Users\SimoneGold\Documents\IPTV Telly Automation\iptv_channels_sunshine.m3u
2018-06-12T19:06:20.017000 saving retrieved m3u file: C:\Users\SimoneGold\Documents\telly\Sorted\original.m3u8
2018-06-12T19:06:20.056000 parsing m3u into a list of objects
2018-06-12T19:06:20.149000 m3u file parse AttributeError: 'NoneType' object has no attribute 'group'
2018-06-12T19:06:20.152000 m3u file parse AttributeError: 'NoneType' object has no attribute 'group'
2018-06-12T19:06:20.152000 m3u file parse AttributeError: 'NoneType' object has no attribute 'group'
2018-06-12T19:06:20.154000 m3u file parse AttributeError: 'NoneType' object has no attribute 'group'
2018-06-12T19:06:20.496000 m3u contains 75601 items
2018-06-12T19:06:20.497000 keeping channel groups in this list['italy']

Traceback (most recent call last): File ".\m3u-epg-editor.py", line 519, in <module> main() File ".\m3u-epg-editor.py", line 127, in main m3u_entries = filter_m3u_entries(args, m3u_entries) File ".\m3u-epg-editor.py", line 290, in filter_m3u_entries if m3u_entry.group_title.lower() in args.groups and not m3u_entry.tvg_name.lower() in args.channels: AttributeError: 'NoneType' object has no attribute 'lower'**

**Comment by jjssoftware** [comment] 2018-06-13 07:20
It's going wrong on this line for you:

https://github.com/jjssoftware/m3u-epg-editor/blob/master/m3u-epg-editor.py#L290

..and the error suggests that the tvg_name attribute within one or more lines in your m3u is empty or just not there. 

If you can take a look inside your m3u file and confirm I'll take a look at the script to see what I can do to cope with it.

**Comment by SimoneGold** [comment] 2018-06-13 11:17
No, I don't see that attribute defined in my m3u. I looked into the Vaders m3u as well, but I don't see it either. So I am a bit confused.

**Comment by jjssoftware** [comment] 2018-06-13 17:27
Yes you've confused me too :) 

I've attached a vaders m3u that was downloaded today at 18:10. I've stripped out all sessionIds. Each stream contains a tvg_name attribute. I have no clue what you're doing or why your m3u stream lines don't contain this attribute. 

I'm going to leave this open a bit longer, feel free to add more info.

[original.13.06.18.18.20.m3u8.zip](https://github.com/jjssoftware/m3u-epg-editor/files/2099180/original.13.06.18.18.20.m3u8.zip)

**Comment by SimoneGold** [comment] 2018-06-13 22:09
I have searched my m3u and I did find **tvg-name** in the channel strings. Does it matter that you wrote it as tvg_name even though it appears as tvg-name in the m3u?

**Comment by jjssoftware** [comment] 2018-06-13 22:20
Sorry my mistake, you're correct it's tvg-name in the m3u file, tvg_name in python code. 

We're not getting anywhere fast here at the moment but I think it might help if you can attach a sanitized version of your m3u file and the complete command line that you're using with it.

**Comment by jjssoftware** [comment] 2018-06-14 07:55
Thanks, that has enabled progress. There's definitely something screwed up in that m3u file that you've attached causing this python script to have issues. I'm not sure where in your m3u file the problem is yet.

I'll run some tests later to try and determine if this is just bad source data or if something needs to be fixed in the script.

**Comment by SimoneGold** [comment] 2018-06-14 12:14
Thanks. Please keep me updated. :)

**Comment by jjssoftware** [comment] 2018-06-14 17:48
I've found the problem entries in your attached m3u file. There are 4 entries that look like they've been corrupted and broken onto two separate lines making them incomplete.

Search for these or parts of these in your m3u file and you'll see the problem.

1. tvg-id="IT: PRIMAFILA 01" tvg-name="IT: PRIMAFILA 01" tvg-logo="http://teamnutz.info/guide/logos/PRIMAFILA.png
2. tvg-id="IT: RSI LA1" tvg-name="IT: RSI LA1" tvg-logo="http://teamnutz.info/guide/logos/RSI%20LA1.png
3. tvg-id="IT: RSI LA2" tvg-name="IT: RSI LA2" tvg-logo="http://teamnutz.info/guide/logos/RSI%20LA2.png
4. tvg-id="" tvg-name="IT: SKY TG24" tvg-logo="http://teamnutz.info/guide/logos/SKY%20TG24.png

These lines have had their group-title attribute drop onto a second line which is causing m3u line parsing to fail. 

From what you've said so far, I think you might be performing some pre-processing on your m3u file and perhaps it's this pre-processor that's causing this data corruption. If that's the case then you might want pursue fixing the pre-processor.

If not I can probably apply a fix to the script to make it cope with these invalid lines in the m3u so it doesn't cause the entire process to fail; the fix would likely be case of ignoring the invalid lines and throwing them away.

How would you like to proceed?

**Comment by SimoneGold** [comment] 2018-06-14 20:48
I would greatly appreciate it if you could apply a patch that would help me get around this. There is no extra step that I believe is in place, so any help on your part would help.

**Closed** 2018-06-14 22:03 UTC
Labels: awaiting feedback

**Comment by jjssoftware** [comment] 2018-06-14 22:04
OK no worries I've applied patch https://github.com/jjssoftware/m3u-epg-editor/commit/2d2b967464f19a98b677138e8f6982fdc7e8a008 which should cope with the invalid data. 

Please pull the latest from master and give it a try thanks.

**Comment by SimoneGold** [comment] 2018-06-15 00:28
Great! Thank you very much :)

**Comment by SimoneGold** [comment] 2018-06-15 00:28
Great! Thank you very much :)
