### ISSUE TITLE
Generated epg.xml does not contain any epg information, just icons

### ISSUE THREAD

**Issue by McRam** [jjssoftware/m3u-epg-editor#61] opened 2021-04-02 18:39 UTC
When using the script it succesfully downloads both original.m3u8 and original.xml files. For the groups/channels that I end up with
 EPG data is present in the original.xml, but nothing ends up in the epg.xml except icon info.

I have attached all files involved. If more info is needed, please let me know.

[epg.zip](https://github.com/jjssoftware/m3u-epg-editor/files/6250853/epg.zip)

**Comment by jjssoftware** [comment] 2021-04-03 00:02
It looks like the script might be having an issue making sense of your source xml. I'm not sure what the cause is yet, I'll run some tests and comment again when I have further details.

**Comment by jjssoftware** [comment] 2021-04-03 08:55
I tested with your input data with python v3.9.2 on linux using script arguments that I guessed from the supplied process.log file and the result was a populated epg.xml file. It appeared to work as it should.

Can you advise specifically which arguments you're using and I'll test again with that, thanks.

**Comment by McRam** [comment] 2021-04-03 09:37
Hello Joe,

Attached is my json file that I use for the input parameters.

[input_args.zip](https://github.com/jjssoftware/m3u-epg-editor/files/6252287/input_args.zip)

I use the native Python docker on my Synology NAS to trigger everything and use the following command:

`docker exec python python /iptv/m3u-epg-editor-py3.py --json_cfg /iptv/input_args.json`

So your generated epg.xml was larger than what was generated on my side? Your assistance is much appreciated!

**Comment by jjssoftware** [comment] 2021-04-03 12:52
Thanks for that, no problem.

I think that I might have got to the bottom of your issue, the problem appears to be related to the time range of programme stop/start attribute data in your source epg.xml. I think that your epg programme data is currently being considered to be invalid and data is being thrown away because you haven't specified a `range` argument value in your json config. 

When a `range` value is not specified, this value automatically defaults to a value of 168hrs (7 days) which causes the script to consider programmes in the epg xml to be valid only when the start/stop time for a programme is now +/- 168hrs.

If you were to add a large `range` value to your json config I think it should resolve this problem.. or it should at least ensure that the newly generated xml file contains programme elements.. but I am unable to say if this epg data will work as expected.

i.e. try something like: `"range": 12000000` in your json config, go again and let me know how that goes, thanks.

**Comment by McRam** [comment] 2021-04-04 08:37
Hi Joe,

Will test today or tomorrow and let you know the results. Again, thanks for your help.

**Comment by McRam** [comment] 2021-04-04 10:46
Hello Joe,

I think I found the reason. It seems my original.xml only contains outdated data. When I look at the timestamps for start of TV shows, I only see dates from February, e.g. 20210215212000. There does not seem to be any recent data in there at all. So feel a bit stupid that I did not see that immediately before posting the issue. So I think it it safe to close the issue.

**Comment by jjssoftware** [comment] 2021-04-04 11:47
No worries, I agree, this is what I described in my previous comment

> the problem appears to be related to the time range of programme stop/start attribute data in your source epg.xml. I think that your epg programme data is currently being considered to be invalid and data is being thrown away because you haven't specified a range argument value in your json config.

This looks like a case of poor quality source epg data. Closing.

**Closed by jjssoftware** 2021-04-04 11:47 UTC
Labels: awaiting feedback, investigation
